export default [
    {
        path:'/homeContent',
        name:'homeContent',
        label:'首页',
        icon:'HomeOutlined',
        url:'/home/index'
    },
    {
        path:'/mall',
        name:'mall',
        label:'商品管理',
        icon:'MailOutlined',
        url:'/mall/index'
    },
    {
        path:'/user',
        name:'user',
        label:'用户管理',
        icon:'UserOutlined',
        url:'/user/index'
    },
    {
        path:'/other',
        label:'其他',
        icon:'SettingOutlined',
        children:[
            {
                path:'/other/pageOne',
                name:'pageOne',
                label:'页面一',
                icon:'SettingOutlined',
            },
            {
                path:'/other/pageTwo',
                name:'pageTwo',
                label:'页面一',
                icon:'SettingOutlined',
            }
        ]
    }
]